version: '3'

services:
  mongodb1:
    image: mongo:latest
    restart: on-failure
    ports:
      - '27017:27017'
    networks:
      - private_network
      - public_network
    volumes:
      - mongo_data_1:/data/db
    entrypoint: [ '/usr/bin/mongod', '--replSet', 'platform', '--bind_ip_all', '--port', '27017' ]

  mongodb2:
    image: mongo:latest
    restart: on-failure
    ports:
      - '27018:27018'
    networks:
      - private_network
      - public_network
    volumes:
      - mongo_data_2:/data/db
    entrypoint: [ '/usr/bin/mongod', '--replSet', 'platform', '--bind_ip_all', '--port', '27018' ]

  mongodb3:
    image: mongo:latest
    restart: on-failure
    ports:
      - '27019:27019'
    networks:
      - private_network
      - public_network
    volumes:
      - mongo_data_3:/data/db
    entrypoint: [ '/usr/bin/mongod', '--replSet', 'platform', '--bind_ip_all', '--port', '27019' ]

  mongodb-initializer:
    image: mongo:latest
    depends_on:
      - mongodb1
      - mongodb2
      - mongodb3
    networks:
      - private_network
    volumes:
      - ./scripts:/scripts
    command:
      - /bin/sh
      - -c
      - |
        sleep 2 &&
        chmod +x /scripts/rs_initializer.sh &&
        /scripts/rs_initializer.sh

networks:
  private_network:
  public_network:
    driver: bridge

volumes:
  mongo_data_1:
  mongo_data_2:
  mongo_data_3:
