version: '3'

services:
  db1:
    image: mongo:latest
    restart: unless-stopped
    ports:
      - '27017:27017'
    networks:
      - private_network
      - public_network
    volumes:
      - db_data_1:/data/db
    entrypoint: [ '/usr/bin/mongod', '--replSet', 'base', '--bind_ip_all', '--port', '27017' ]

  db2:
    image: mongo:latest
    restart: unless-stopped
    ports:
      - '27018:27018'
    networks:
      - private_network
      - public_network
    volumes:
      - db_data_2:/data/db
    entrypoint: [ '/usr/bin/mongod', '--replSet', 'base', '--bind_ip_all', '--port', '27018' ]

  db3:
    image: mongo:latest
    restart: unless-stopped
    ports:
      - '27019:27019'
    networks:
      - private_network
      - public_network
    volumes:
      - db_data_3:/data/db
    entrypoint: [ '/usr/bin/mongod', '--replSet', 'base', '--bind_ip_all', '--port', '27019' ]

  mongodb-initializer:
    image: mongo:latest
    depends_on:
      - db1
      - db2
      - db3
    networks:
      - private_network
    volumes:
      - ./scripts:/scripts
    command:
      - /bin/sh
      - -c
      - |
        sleep 2 &&
        chmod +x /scripts/rs_initializer.sh &&
        /scripts/rs_initializer.sh

networks:
  private_network:
  public_network:
    driver: bridge

volumes:
  db_data_1:
  db_data_2:
  db_data_3:
