name: 'Deploy'

on:
  push:
    branches:
      # - 'main'
      - 'feature/turborepo-migration'
    paths:
      - 'apps/**'
      - 'packages/**'

env:
  #  Vercel
  VERCEL_TOKEN: '${{ secrets.VERCEL_TOKEN }}'
  VERCEL_BACKEND_APP_NAME: '${{ secrets.VERCEL_BACKEND_APP_NAME }}'
  VERCEL_BACKEND_ORGANIZATION_ID: '${{ secrets.VERCEL_BACKEND_ORGANIZATION_ID }}'
  VERCEL_BACKEND_PROJECT_ID: '${{ secrets.VERCEL_BACKEND_PROJECT_ID }}'
  VERCEL_ADMIN_APP_NAME: '${{ secrets.VERCEL_ADMIN_APP_NAME }}'
  VERCEL_ADMIN_ORGANIZATION_ID: '${{ secrets.VERCEL_ADMIN_ORGANIZATION_ID }}'
  VERCEL_ADMIN_PROJECT_ID: '${{ secrets.VERCEL_ADMIN_PROJECT_ID }}'
  VERCEL_FRONTEND_APP_NAME: '${{ secrets.VERCEL_FRONTEND_APP_NAME }}'
  VERCEL_FRONTEND_ORGANIZATION_ID: '${{ secrets.VERCEL_FRONTEND_ORGANIZATION_ID }}'
  VERCEL_FRONTEND_PROJECT_ID: '${{ secrets.VERCEL_FRONTEND_PROJECT_ID }}'

  #  Backend
  DATABASE_URL: '${{ secrets.DATABASE_URL }}'
  JWT_SECRET: '${{ secrets.JWT_SECRET }}'
  ADMIN_URL: '${{ secrets.ADMIN_URL }}'
  FRONTEND_URL: '${{ secrets.FRONTEND_URL }}'
  BACKEND_URL: '${{ secrets.BACKEND_URL }}'
  BCRYPT_SALT: '${{ secrets.BCRYPT_SALT }}'

  #  Admin
  NEXT_PUBLIC_BACKEND_URL: '${{ secrets.BACKEND_URL }}'

  #  Frontend

  #  Github
  GITHUB_BASE_URL: 'https://${{ github.repository_owner }}.github.io'
  GITHUB_REPOSITORY_URL: 'https://github.com/${{ github.repository }}'
  GITHUB_COMMIT_MESSAGE: '${{ github.event.head_commit.message }}'
  GITHUB_COMMITTER: '${{ github.actor }}'

jobs:
  Deploy:
    runs-on: 'ubuntu-latest'

    steps:
      - uses: 'actions/checkout@v3'
      - name: 'Setup node'
        uses: 'actions/setup-node@v3'
        with:
          node-version: 18
      - name: 'Install dependencies'
        run: 'npm install'

      # CHECK CHANGED FILES

      - name: 'Check changed files'
        uses: 'dorny/paths-filter@v3'
        id: 'changes-filter'
        with:
          base: '${{ github.ref }}'
          filters: |
            backend:
              - 'apps/backend/**'
            admin:
              - 'apps/admin/**'
            frontend:
              - 'apps/frontend/**'
            packages:
              - 'packages/**'

      # VERCEL DEPLOYMENT

      - name: 'Vercel deployment'
        run: |
          chmod +x scripts/vercel/deploy.sh
          scripts/vercel/deploy.sh
        env:
          DEPLOYMENT_TARGETS: '${{ toJson(steps.changes-filter.outputs) }}'

        # GITHUB

#      - name: 'Prepare frontend github version'
#        if: steps.changes-filter.outputs.frontend == 'true' || steps.changes-filter.outputs.packages == 'true'
#        run: 'chmod +x scripts/github/prepare.sh && scripts/github/prepare.sh'
#      - name: 'Deploy frontend github version'
#        if: steps.changes-filter.outputs.frontend == 'true' || steps.changes-filter.outputs.packages == 'true'
#        uses: 'peaceiris/actions-gh-pages@v3'
#        with:
#          github_token: '${{ secrets.GITHUB_TOKEN }}'
#          publish_dir: './apps/frontend/dist/frontend/browser'
